export const COPY = {
    es: {
        photoAlt: "Equipo ARC.LAB en una sesión de movilidad en el gimnasio",
        marquee: ["in-season", "mantener", "gestionar", "rendir", "arc.lab · performance"],
        nav: { planes: "Planes", jugadores: "Jugadores", dudas: "Dudas", cta: "Escríbenos" },
        hero: {
            eyebrow: "ARC.LAB · In-Season",
            titlePre: "tu primer plan",
            titleEm: "de verdad.",
            sub: "Preparación física para jugadores de baloncesto que quieren dar el salto.",
            cta1: "Escríbenos",
            cta2: "Ver los planes",
        },
        problema: {
            titlePre: "entrenar mucho no es entrenar",
            titleEm: "bien.",
            lines: [
                "Copias ejercicios de Instagram sin saber si te sirven a ti.",
                "Sigues rutinas hechas para cualquiera — no para ti.",
                "A nadie le importa cómo te sientes: mientras entrenes, todo vale.",
            ],
            closePre: "El siguiente nivel no se improvisa.",
            closeEm: "Se planifica.",
        },
        enfoque: {
            eyebrow: "El enfoque · In-Season",
            titlePre: "tu mejor versión,",
            titleEm: "toda la temporada.",
            steps: [
                {
                    n: "01",
                    title: "Rendimiento",
                    text: "Que lo notes en la pista: más fuerte en el contacto, más explosivo y con piernas para más minutos.",
                },
                {
                    n: "02",
                    title: "Fatiga",
                    text: "Ajustamos tu plan cada semana, al detalle — hablando contigo, según cómo te sientes y tu carga de pista.",
                },
                {
                    n: "03",
                    title: "Día de partido",
                    text: "Todo el trabajo apunta a una cosa: llegar al día de partido ligero, explosivo y preparado.",
                },
            ],
        },
        club: {
            eyebrow: "El club y tú",
            titlePre: "el trabajo de equipo te mantiene. el individual te hace",
            titleEm: "subir.",
            paraPre:
                "El trabajo físico del club muchas veces se queda corto para quien busca mejoras de verdad. No es culpa de nadie — es imposible afinar el trabajo de doce jugadores a la vez. Pero ese trabajo, si quieres subir,",
            paraStrong: "alguien tiene que hacerlo contigo.",
        },
        planes: {
            eyebrow: "Los planes · Mensualidad",
            titlePre: "elige tu nivel de",
            titleEm: "acompañamiento.",
            note: "Sin permanencia. Mensualidad: empiezas cuando quieras y cambias de plan según tu temporada.",
            cards: [
                {
                    id: "basic",
                    name: "Basic",
                    tag: "Autonomía con guía",
                    price: "50€",
                    unit: "/mes",
                    claim: "Tú al mando, con estructura.",
                    features: [
                        "Cuestionario inicial escrito",
                        "Plan mensual de fuerza y prevención",
                        "Actualización mensual",
                        "Dudas puntuales por WhatsApp",
                    ],
                    cta: "Escríbenos",
                    style: "bone",
                    msg: "basic",
                },
                {
                    id: "pro",
                    name: "Pro",
                    tag: "Seguimiento cercano",
                    badge: "El más vendido",
                    price: "95€",
                    unit: "/mes",
                    claim: "Tu plan, vivo cada semana.",
                    features: [
                        "Valoración inicial",
                        "Adaptado a tu calendario y material",
                        "Actualización quincenal",
                        "Revisión continuada de carga",
                        "Videollamada mensual",
                    ],
                    cta: "Escríbenos",
                    style: "featured",
                    msg: "pro",
                },
                {
                    id: "duo",
                    name: "Duo",
                    tag: "Pro, para dos",
                    price: "80€",
                    unit: "/jugador",
                    priceSmall: "160€/mes los dos",
                    claim: "Todo lo del Pro, para dos.",
                    features: [
                        "El plan Pro completo, para dos",
                        "Cada uno su plan y su calendario",
                        "Mismo seguimiento, mejor precio",
                    ],
                    cta: "Escríbenos",
                    style: "bone",
                    msg: "duo",
                },
                {
                    id: "elite",
                    name: "Elite",
                    tag: "Máximo seguimiento",
                    price: "220€",
                    unit: "/mes",
                    claim: "Sólo 2 plazas por temporada.",
                    features: [
                        "Todo lo del Pro",
                        "Actualización y videollamada semanal",
                        "WhatsApp prioritario",
                        "Activación pre-partido y check-in post",
                        "Nutrición incluida (guía + seguimiento)",
                        "Coordinación con tu club o fisio",
                        "Informe mensual de tu temporada",
                    ],
                    cta: "Pedir plaza",
                    style: "dark",
                    msg: "elite",
                },
            ],
            after1: "Empieza en",
            afterB1: "Basic",
            after2: "y sube a",
            afterB2: "Pro",
            after3: "cuando quieras, sin coste de cambio. · Precios finales, sin sorpresas.",
            compare: {
                label: "Compara los planes al detalle",
                rows: [
                    ["Plan de fuerza y prevención personalizado", "✓", "✓", "✓"],
                    ["Adaptado a tu calendario y a tu material", "—", "✓", "✓"],
                    ["Actualización del plan", "Mensual", "Quincenal", "Semanal"],
                    ["Valoración inicial", "Cuestionario", "✓", "✓"],
                    ["Registro de entreno y wellness", "—", "✓", "✓"],
                    ["Revisión continuada de carga", "—", "✓", "✓"],
                    ["Videollamada de seguimiento", "—", "Mensual", "Semanal"],
                    ["Contacto por WhatsApp", "Dudas puntuales", "Según horario", "Prioritario"],
                    ["Activación pre-partido y recuperación post", "—", "—", "✓"],
                    ["Check-in post-partido", "—", "—", "✓"],
                    ["Nutrición (guía + seguimiento)", "—", "—", "Incluido"],
                    ["Coordinación con tu club o fisio", "—", "—", "✓"],
                    ["Informe mensual de tu temporada", "—", "—", "✓"],
                ],
            },
            band: {
                pre: "¿Dudas entre dos planes?",
                strong: "Escríbenos y te decimos cuál encaja contigo.",
                cta: "Hablar por WhatsApp",
            },
        },
        prueba: {
            eyebrow: "Prueba · Programa 01 → 02",
            titlePre: "palabra de",
            titleEm: "jugador.",
            quote: "El trabajo de cada semana se nota el día del partido.",
            photoLabel: "Foto del atleta",
            athletes: [
                { meta: "Alex Almenta · 2ª FEB", img: "/images/athlete-1.jpg" },
                { meta: "Nombre · Liga · Posición" },
                { meta: "Nombre · Liga · Posición" },
            ],
        },
        faq: {
            eyebrow: "Dudas frecuentes",
            titlePre: "lo que todos",
            titleEm: "preguntan.",
            items: [
                {
                    q: "¿Puede ser mi única preparación física?",
                    a: "Sí. El plan cubre fuerza, prevención y preparación completa para tu temporada. Si no tienes preparador en el club, esto es tu estructura entera.",
                },
                {
                    q: "¿Y si mi club ya tiene preparador?",
                    a: "Mejor. Complementamos el trabajo del club con lo individual — tu carga, tus molestias, tu semana. En Elite nos coordinamos directamente con tu club.",
                },
                {
                    q: "¿Y si no tengo gimnasio?",
                    a: "El plan se diseña con el material que tienes de verdad. Lo que no vamos a hacer es darte un plan que no puedas cumplir.",
                },
                {
                    q: "¿Puedo empezar a mitad de temporada?",
                    a: "Sí. La valoración inicial sirve exactamente para eso: saber dónde estás hoy y construir desde ahí.",
                },
                {
                    q: "¿Cuánto tiempo me va a pedir por semana?",
                    a: "Normalmente 2 a 4 sesiones que encajan alrededor de tus entrenos de equipo. El plan se adapta a tu semana, no al revés.",
                },
                {
                    q: "¿Qué pasa si me lesiono o tengo que parar?",
                    a: "No hay permanencia: si necesitas parar, simplemente no renuevas el mes siguiente. Y si es una molestia leve, ajustamos el plan para seguir trabajando lo que sí puedas.",
                },
                {
                    q: "¿Cómo funcionan los pagos?",
                    a: "Mensualidad, sin permanencia y sin letra pequeña. Empiezas cuando quieras y cambias de plan cuando tu temporada lo pida.",
                },
            ],
        },
        empezar: {
            eyebrow: "Empezar",
            titlePre: "¿empezamos?",
            titleEm: "escríbenos",
            titlePost: "y lo hablamos.",
            subPre:
                "Cuéntanos tu momento y tu calendario. Te decimos qué plan encaja contigo —",
            subStrong: "sin compromiso.",
            responsePre: "Te respondemos en",
            responseStrong: "menos de 24h.",
            countries: { es: "España", pt: "Portugal" },
            legal: "Precios y condiciones actuales. El acompañamiento nutricional es educativo y no sustituye la valoración de un nutricionista colegiado.",
        },
        footer: { motto1: "Nada porque sí.", motto2: "Todo por una razón." },
    },
    pt: {
        photoAlt: "Equipa ARC.LAB numa sessão de mobilidade no ginásio",
        marquee: ["in-season", "manter", "gerir", "render", "arc.lab · performance"],
        nav: { planes: "Planos", jugadores: "Jogadores", dudas: "Dúvidas", cta: "Escreve-nos" },
        hero: {
            eyebrow: "ARC.LAB · In-Season",
            titlePre: "o teu primeiro plano",
            titleEm: "a sério.",
            sub: "Preparação física para jogadores de basquetebol que querem dar o salto.",
            cta1: "Escreve-nos",
            cta2: "Ver os planos",
        },
        problema: {
            titlePre: "treinar muito não é treinar",
            titleEm: "bem.",
            lines: [
                "Copias exercícios do Instagram sem saber se servem para ti.",
                "Segues rotinas feitas para qualquer um — não para ti.",
                "A ninguém interessa como te sentes: enquanto treinares, tudo vale.",
            ],
            closePre: "O próximo nível não se improvisa.",
            closeEm: "Planeia-se.",
        },
        enfoque: {
            eyebrow: "O enfoque · In-Season",
            titlePre: "a tua melhor versão,",
            titleEm: "toda a época.",
            steps: [
                {
                    n: "01",
                    title: "Rendimento",
                    text: "Que o notes na pista: mais forte no contacto, mais explosivo e com pernas para mais minutos.",
                },
                {
                    n: "02",
                    title: "Fadiga",
                    text: "Ajustamos o teu plano todas as semanas, ao detalhe — a falar contigo, conforme te sentes e a tua carga de pista.",
                },
                {
                    n: "03",
                    title: "Dia de jogo",
                    text: "Todo o trabalho aponta para uma coisa: chegar ao dia de jogo leve, explosivo e preparado.",
                },
            ],
        },
        club: {
            eyebrow: "O clube e tu",
            titlePre: "o trabalho de equipa mantém-te. o individual faz-te",
            titleEm: "subir.",
            paraPre:
                "O trabalho físico do clube muitas vezes fica curto para quem procura melhorias a sério. Não é culpa de ninguém — é impossível afinar o trabalho de doze jogadores ao mesmo tempo. Mas esse trabalho, se queres subir,",
            paraStrong: "alguém tem de o fazer contigo.",
        },
        planes: {
            eyebrow: "Os planos · Mensalidade",
            titlePre: "escolhe o teu nível de",
            titleEm: "acompanhamento.",
            note: "Sem permanência. Mensalidade: começas quando quiseres e mudas de plano conforme a tua época.",
            cards: [
                {
                    id: "basic",
                    name: "Basic",
                    tag: "Autonomia com guia",
                    price: "50€",
                    unit: "/mês",
                    claim: "Tu ao comando, com estrutura.",
                    features: [
                        "Questionário inicial escrito",
                        "Plano mensal de força e prevenção",
                        "Atualização mensal",
                        "Dúvidas pontuais por WhatsApp",
                    ],
                    cta: "Escreve-nos",
                    style: "bone",
                    msg: "basic",
                },
                {
                    id: "pro",
                    name: "Pro",
                    tag: "Acompanhamento próximo",
                    badge: "O mais vendido",
                    price: "95€",
                    unit: "/mês",
                    claim: "O teu plano, vivo todas as semanas.",
                    features: [
                        "Avaliação inicial",
                        "Adaptado ao teu calendário e material",
                        "Atualização quinzenal",
                        "Revisão contínua de carga",
                        "Videochamada mensal",
                    ],
                    cta: "Escreve-nos",
                    style: "featured",
                    msg: "pro",
                },
                {
                    id: "duo",
                    name: "Duo",
                    tag: "Pro, para dois",
                    price: "80€",
                    unit: "/jogador",
                    priceSmall: "160€/mês os dois",
                    claim: "Tudo o do Pro, para dois.",
                    features: [
                        "O plano Pro completo, para dois",
                        "Cada um o seu plano e o seu calendário",
                        "O mesmo acompanhamento, melhor preço",
                    ],
                    cta: "Escreve-nos",
                    style: "bone",
                    msg: "duo",
                },
                {
                    id: "elite",
                    name: "Elite",
                    tag: "Máximo acompanhamento",
                    price: "220€",
                    unit: "/mês",
                    claim: "Só 2 vagas por época.",
                    features: [
                        "Tudo o do Pro",
                        "Atualização e videochamada semanal",
                        "WhatsApp prioritário",
                        "Ativação pré-jogo e check-in pós",
                        "Nutrição incluída (guia + acompanhamento)",
                        "Coordenação com o teu clube ou fisio",
                        "Relatório mensal da tua época",
                    ],
                    cta: "Pedir vaga",
                    style: "dark",
                    msg: "elite",
                },
            ],
            after1: "Começa no",
            afterB1: "Basic",
            after2: "e sobe para",
            afterB2: "Pro",
            after3: "quando quiseres, sem custo de mudança. · Preços finais, sem surpresas.",
            compare: {
                label: "Compara os planos ao detalhe",
                rows: [
                    ["Plano de força e prevenção personalizado", "✓", "✓", "✓"],
                    ["Adaptado ao teu calendário e ao teu material", "—", "✓", "✓"],
                    ["Atualização do plano", "Mensal", "Quinzenal", "Semanal"],
                    ["Avaliação inicial", "Questionário", "✓", "✓"],
                    ["Registo de treino e wellness", "—", "✓", "✓"],
                    ["Revisão contínua de carga", "—", "✓", "✓"],
                    ["Videochamada de acompanhamento", "—", "Mensal", "Semanal"],
                    ["Contacto por WhatsApp", "Dúvidas pontuais", "Conforme horário", "Prioritário"],
                    ["Ativação pré-jogo e recuperação pós", "—", "—", "✓"],
                    ["Check-in pós-jogo", "—", "—", "✓"],
                    ["Nutrição (guia + acompanhamento)", "—", "—", "Incluído"],
                    ["Coordenação com o teu clube ou fisio", "—", "—", "✓"],
                    ["Relatório mensal da tua época", "—", "—", "✓"],
                ],
            },
            band: {
                pre: "Dúvidas entre dois planos?",
                strong: "Escreve-nos e dizemos-te qual encaixa contigo.",
                cta: "Falar no WhatsApp",
            },
        },
        prueba: {
            eyebrow: "Prova · Programa 01 → 02",
            titlePre: "palavra de",
            titleEm: "jogador.",
            quote: "O trabalho de cada semana nota-se no dia do jogo.",
            photoLabel: "Foto do atleta",
            athletes: [
                { meta: "Alex Almenta · 2ª FEB", img: "/images/athlete-1.jpg" },
                { meta: "Nome · Liga · Posição" },
                { meta: "Nome · Liga · Posição" },
            ],
        },
        faq: {
            eyebrow: "Dúvidas frequentes",
            titlePre: "o que todos",
            titleEm: "perguntam.",
            items: [
                {
                    q: "Pode ser a minha única preparação física?",
                    a: "Sim. O plano cobre força, prevenção e preparação completa para a tua época. Se não tens preparador no clube, isto é a tua estrutura inteira.",
                },
                {
                    q: "E se o meu clube já tem preparador?",
                    a: "Melhor. Complementamos o trabalho do clube com o individual — a tua carga, as tuas mazelas, a tua semana. No Elite coordenamo-nos diretamente com o teu clube.",
                },
                {
                    q: "E se não tiver ginásio?",
                    a: "O plano é desenhado com o material que tens a sério. O que não vamos fazer é dar-te um plano que não consigas cumprir.",
                },
                {
                    q: "Posso começar a meio da época?",
                    a: "Sim. A avaliação inicial serve exatamente para isso: saber onde estás hoje e construir a partir daí.",
                },
                {
                    q: "Quanto tempo me vai pedir por semana?",
                    a: "Normalmente 2 a 4 sessões que encaixam à volta dos teus treinos de equipa. O plano adapta-se à tua semana, não ao contrário.",
                },
                {
                    q: "O que acontece se me lesionar ou tiver de parar?",
                    a: "Não há permanência: se precisares de parar, simplesmente não renovas o mês seguinte. E se for uma mazela leve, ajustamos o plano para continuar a trabalhar o que puderes.",
                },
                {
                    q: "Como funcionam os pagamentos?",
                    a: "Mensalidade, sem permanência e sem letras pequenas. Começas quando quiseres e mudas de plano quando a tua época o pedir.",
                },
            ],
        },
        empezar: {
            eyebrow: "Começar",
            titlePre: "começamos?",
            titleEm: "escreve-nos",
            titlePost: "e falamos.",
            subPre:
                "Conta-nos o teu momento e o teu calendário. Dizemos-te que plano encaixa contigo —",
            subStrong: "sem compromisso.",
            responsePre: "Respondemos-te em",
            responseStrong: "menos de 24h.",
            countries: { es: "Espanha", pt: "Portugal" },
            legal: "Preços e condições atuais. O acompanhamento nutricional é educativo e não substitui a avaliação de um nutricionista certificado.",
        },
        footer: { motto1: "Nada porque sí.", motto2: "Todo por una razón." },
    },
};
