export const COPY = {
    es: {
        whatsapp: "WhatsApp",
        headerProgram: "Programa · Nº 01 · In-Season — ARC.LAB · Performance",
        photoAlt: "Equipo ARC.LAB en una sesión de movilidad en el gimnasio",
        hero: {
            eyebrow: "— Durante la temporada",
            line1: "el partido se gana",
            line2pre: "entre",
            line2em: "partidos.",
            sub: "Mantener el nivel, gestionar la fatiga y llegar entero a cada semana.",
            cta: "Hablar por WhatsApp",
            plans: "Ver los planes",
        },
        marquee: [
            "in-season",
            "mantener",
            "gestionar",
            "rendir",
            "arc.lab · performance",
        ],
        enfoque: {
            eyebrow: "— El enfoque · In-Season",
            title1: "en temporada no se carga.",
            titleEm: "se mantiene.",
            paraPre: "Ya compites cada semana. El trabajo no es acumular, es",
            paraStrong: "llegar entero y rendir el día del partido",
            paraPost:
                "— ajustando la carga a tu semana real: minutos, viajes, dobles jornadas y molestias.",
            cards: [
                {
                    n: "01",
                    title: "Rendimiento",
                    text: "Mantener tu nivel físico durante toda la temporada, sin altibajos.",
                },
                {
                    n: "02",
                    title: "Fatiga",
                    text: "Gestionar carga, viajes y minutos con registro diario y ajuste continuo.",
                },
                {
                    n: "03",
                    title: "Día de partido",
                    text: "Activación antes y recuperación después, para competir al máximo.",
                },
            ],
            closeTitle: "tu semana,",
            closeEm: "tu carga.",
            closePre: "No hay dos semanas iguales.",
            closeStrong: "Ajustamos tu plan según cómo llegas",
            closePost: "— según tu feedback, no según un calendario fijo.",
        },
        planes: {
            eyebrow: "— Los planes · Mensualidad",
            titlePre: "elige tu nivel de",
            titleEm: "acompañamiento.",
            featured: "El más vendido",
            cta: "Hablar por WhatsApp",
            list: [
                {
                    id: "basic",
                    name: "Basic",
                    tag: "Autonomía con guía",
                    price: "50€",
                    unit: "/mes",
                    blurb: "Tú al mando, con estructura.",
                    features: [
                        "Plan mensual de fuerza y prevención según tu calendario",
                        "Actualización según tu semana de partidos",
                        "Registro diario y ajustes por feedback",
                        "Guía de hábitos nutricionales",
                    ],
                },
                {
                    id: "normal",
                    name: "Normal",
                    tag: "Acompañamiento cercano",
                    price: "85€",
                    unit: "/mes",
                    blurb: "Todo lo Basic, con seguimiento individual.",
                    featured: true,
                    features: [
                        "Todo lo de Basic",
                        "Revisión individual cada 2 semanas (vídeo o llamada)",
                        "Ajustes por minutos jugados y molestias",
                        "Activación pre-partido y recuperación",
                    ],
                },
                {
                    id: "duo",
                    name: "Duo",
                    tag: "Normal, para dos",
                    price: "150€",
                    unit: "/mes · 2 jugadores",
                    blurb: "75€ por jugador.",
                    features: [
                        "El plan Normal para 2 que entrenan juntos",
                        "Mismo seguimiento, mejor precio por cabeza",
                        "Mismo calendario / entrenáis juntos",
                    ],
                },
                {
                    id: "pro",
                    name: "Pro",
                    tag: "Máximo seguimiento",
                    price: "220€",
                    unit: "/mes",
                    blurb: "Plazas muy limitadas.",
                    features: [
                        "Seguimiento cercano semanal y contacto prioritario",
                        "Acompañamiento nutricional (hábitos + timing)",
                        "Revaluaciones periódicas de tu nivel",
                        "Coordinación con tu club o físio",
                    ],
                },
            ],
        },
        extras: {
            eyebrow: "— Extras & Continuidad",
            blocks: [
                {
                    id: "nutricion",
                    tag: "Extra · Nutrición",
                    title: "Súmale la nutrición",
                    text: "Acompañamiento nutricional como añadido (+35€/mes) en Basic y Normal. Hábitos y educación — no sustituye a un nutricionista.",
                },
                {
                    id: "pack",
                    tag: "Pack Temporada",
                    title: "Toda la temporada",
                    text: "Paga la temporada completa por adelantado y ahorra. Continuidad desde el verano, sin cuota de valoración.",
                },
            ],
        },
        contacto: {
            titlePre: "¿empezamos?",
            titleEm: "escríbenos y lo hablamos.",
            sub: "Cuéntanos tu momento y tu calendario. Te decimos qué plan encaja contigo.",
            legal: "La valoración inicial no tiene coste. El acompañamiento de ARC.LAB complementa —nunca sustituye— el seguimiento médico ni el trabajo del preparador físico de tu club. [Texto legal definitivo pendiente de confirmar.]",
        },
        footer: { tiktok: "TikTok — próximamente" },
    },
    pt: {
        whatsapp: "WhatsApp",
        headerProgram: "Programa · Nº 01 · In-Season — ARC.LAB · Performance",
        photoAlt: "Equipa ARC.LAB numa sessão de mobilidade no ginásio",
        hero: {
            eyebrow: "— Durante a época",
            line1: "o jogo ganha-se",
            line2pre: "entre",
            line2em: "jogos.",
            sub: "Manter o nível, gerir a fadiga e chegar inteiro a cada semana.",
            cta: "Falar no WhatsApp",
            plans: "Ver os planos",
        },
        marquee: [
            "in-season",
            "manter",
            "gerir",
            "render",
            "arc.lab · performance",
        ],
        enfoque: {
            eyebrow: "— O enfoque · In-Season",
            title1: "em época não se carrega.",
            titleEm: "mantém-se.",
            paraPre:
                "Já competes todas as semanas. O trabalho não é acumular, é",
            paraStrong: "chegar inteiro e render no dia do jogo",
            paraPost:
                "— ajustando a carga à tua semana real: minutos, viagens, jornadas duplas e mazelas.",
            cards: [
                {
                    n: "01",
                    title: "Rendimento",
                    text: "Manter o teu nível físico durante toda a época, sem altos e baixos.",
                },
                {
                    n: "02",
                    title: "Fadiga",
                    text: "Gerir carga, viagens e minutos com registo diário e ajuste contínuo.",
                },
                {
                    n: "03",
                    title: "Dia de jogo",
                    text: "Ativação antes e recuperação depois, para competir ao máximo.",
                },
            ],
            closeTitle: "a tua semana,",
            closeEm: "a tua carga.",
            closePre: "Não há duas semanas iguais.",
            closeStrong: "Ajustamos o teu plano conforme chegas",
            closePost: "— conforme o teu feedback, não conforme um calendário fixo.",
        },
        planes: {
            eyebrow: "— Os planos · Mensalidade",
            titlePre: "escolhe o teu nível de",
            titleEm: "acompanhamento.",
            featured: "O mais vendido",
            cta: "Falar no WhatsApp",
            list: [
                {
                    id: "basic",
                    name: "Basic",
                    tag: "Autonomia com guia",
                    price: "50€",
                    unit: "/mês",
                    blurb: "Tu ao comando, com estrutura.",
                    features: [
                        "Plano mensal de força e prevenção conforme o teu calendário",
                        "Atualização conforme a tua semana de jogos",
                        "Registo diário e ajustes por feedback",
                        "Guia de hábitos nutricionais",
                    ],
                },
                {
                    id: "normal",
                    name: "Normal",
                    tag: "Acompanhamento próximo",
                    price: "85€",
                    unit: "/mês",
                    blurb: "Tudo o Basic, com acompanhamento individual.",
                    featured: true,
                    features: [
                        "Tudo o do Basic",
                        "Revisão individual a cada 2 semanas (vídeo ou chamada)",
                        "Ajustes por minutos jogados e mazelas",
                        "Ativação pré-jogo e recuperação",
                    ],
                },
                {
                    id: "duo",
                    name: "Duo",
                    tag: "Normal, para dois",
                    price: "150€",
                    unit: "/mês · 2 jogadores",
                    blurb: "75€ por jogador.",
                    features: [
                        "O plano Normal para 2 que treinam juntos",
                        "O mesmo acompanhamento, melhor preço por cabeça",
                        "Mesmo calendário / treinam juntos",
                    ],
                },
                {
                    id: "pro",
                    name: "Pro",
                    tag: "Máximo acompanhamento",
                    price: "220€",
                    unit: "/mês",
                    blurb: "Vagas muito limitadas.",
                    features: [
                        "Acompanhamento próximo semanal e contacto prioritário",
                        "Acompanhamento nutricional (hábitos + timing)",
                        "Reavaliações periódicas do teu nível",
                        "Coordenação com o teu clube ou fisioterapeuta",
                    ],
                },
            ],
        },
        extras: {
            eyebrow: "— Extras & Continuidade",
            blocks: [
                {
                    id: "nutricion",
                    tag: "Extra · Nutrição",
                    title: "Soma a nutrição",
                    text: "Acompanhamento nutricional como extra (+35€/mês) no Basic e Normal. Hábitos e educação — não substitui um nutricionista.",
                },
                {
                    id: "pack",
                    tag: "Pack Época",
                    title: "Toda a época",
                    text: "Paga a época completa antecipadamente e poupa. Continuidade desde o verão, sem quota de avaliação.",
                },
            ],
        },
        contacto: {
            titlePre: "começamos?",
            titleEm: "fala connosco.",
            sub: "Conta-nos o teu momento e o teu calendário. Dizemos-te que plano encaixa contigo.",
            legal: "A avaliação inicial não tem custo. O acompanhamento da ARC.LAB complementa — nunca substitui — o acompanhamento médico nem o trabalho do preparador físico do teu clube. [Texto legal definitivo por confirmar.]",
        },
        footer: { tiktok: "TikTok — em breve" },
    },
};
