export const COPY = {
    es: {
        marquee: ["in-season", "mantener", "gestionar", "rendir", "arc.lab · performance"],
        nav: {
            entrenamiento: "Entrenamiento",
            comoFunciona: "Cómo funciona",
            planes: "Planes",
            sobre: "Sobre arc.lab",
            cta: "Empezar ahora",
        },
        hero: {
            eyebrow: "ARC.LAB · In-Season",
            titleL1: "tu primer",
            titleL2: "plan de",
            titleEm: "verdad.",
            sub: "Entrenamiento personal para jugadores de baloncesto que quieren más.",
            bandWords: ["Ciencia.", "Disciplina.", "Mentalidad.", "Resultados."],
            footNote: "Arc.Lab Training System",
            photoAlt: "Jugador de baloncesto en pleno mate, en el pico del salto",
            cta1: "Empezar ahora",
            cta2: "Ver planes",
        },
        problema: {
            titleL1: "entrenar mucho",
            titleL2: "no es entrenar",
            titleEm: "bien.",
            sub: "Haces el esfuerzo, pero los resultados no llegan.",
            photoLabel: "Foto — esfuerzo real",
            problems: [
                {
                    n: "01",
                    title: "Sin dirección",
                    text: "Entrenas sin un plan claro y no sabes si avanzas.",
                    detail: "Cada semana entrenas algo distinto, según el ánimo o lo que ves en redes. Sin progresión ni objetivos claros, la constancia no se convierte en mejora. Necesitas un plan que te diga qué hacer y por qué.",
                },
                {
                    n: "02",
                    title: "Demasiado esfuerzo",
                    text: "Pocos resultados. Te desgastas sin ver mejoras reales.",
                    detail: "Acumulas sesiones y cansancio, pero nadie ajusta la carga a tu calendario de partidos. El esfuerzo sin medida no suma: desgasta. Y el desgaste continuado termina en molestias o lesión.",
                },
                {
                    n: "03",
                    title: "Sin conexión con el juego",
                    text: "Lo que haces en el gym no se traduce en la cancha.",
                    detail: "Levantas más peso, pero no saltas más ni frenas mejor. El gimnasio y la cancha parecen dos deportes distintos. La fuerza solo importa cuando se convierte en gestos de baloncesto.",
                },
                {
                    n: "04",
                    title: "Sin seguimiento",
                    text: "Nadie revisa tu carga ni ajusta el plan cuando tu semana cambia.",
                    detail: "El plan de enero ya no te sirve en marzo: cambian los partidos, los entrenos y cómo responde tu cuerpo. Sin revisiones, entrenas con información vieja. El seguimiento es lo que convierte un PDF en un programa.",
                },
            ],
        },
        solucion: {
            titleL1: "un plan",
            titleL2: "que se mueve",
            titleEm: "contigo.",
            sub1: "Tu cuerpo, tu carga, tu calendario y tu partido.",
            sub2: "Todo conectado. Todo adaptado a ti.",
            photoLabel: "Foto — trabajo en equipo",
            items: [
                { title: "Cuerpo", text: "Entendemos tu perfil y tus necesidades." },
                { title: "Carga", text: "Diseñamos tu plan específico." },
                { title: "Calendario", text: "Organizamos tu semana y tu progresión." },
                { title: "Partido", text: "Transferimos al juego lo que entrenas." },
            ],
        },
        metodo: {
            titleL1: "hecho",
            titleL2: "para tu",
            titleEm: "juego.",
            sub: "Tu físico tiene que entender tu juego.",
            photoLabel: "Foto — jugadora en acción",
            steps: [
                {
                    n: "01",
                    title: "Evaluamos",
                    text: "Entendemos tu perfil atlético, tu historial y las demandas de tu posición.",
                },
                {
                    n: "02",
                    title: "Preparamos",
                    text: "Diseñamos un plan específico que desarrolla lo que tu juego realmente exige.",
                },
                {
                    n: "03",
                    title: "Rendimos",
                    text: "Entrenas con intención. Compites con ventaja. Evolucionas cada día.",
                },
            ],
        },
        cambios: {
            outcomes: [
                {
                    pre: "Más",
                    word: "fuerza",
                    text: "Fuerza que se nota en cada contacto: entradas al aro, rebotes y cambios de ritmo con otro cuerpo.",
                },
                {
                    pre: "Más",
                    word: "explosividad",
                    text: "Primer paso más rápido, saltos más altos y acciones repetidas sin perder potencia.",
                },
                {
                    pre: "Menos",
                    word: "fatiga",
                    text: "Carga bien gestionada para llegar fresco al último cuarto. Y al próximo partido.",
                },
                {
                    pre: "Más",
                    word: "control",
                    text: "Sabes qué entrenas, cuándo y por qué. Cada sesión con un objetivo claro.",
                },
            ],
        },
        planes: {
            eyebrow: "Los planes",
            eyebrow2: "Mensualidad",
            titleL1: "elige tu nivel",
            titleL2: "de",
            titleEm: "acompañamiento.",
            sub: "Más estructura. Más resultados. Más tú.",
            note: "Sin permanencia. Mensualidad: empiezas cuando quieras y cambias de plan según tu temporada.",
            cards: [
                {
                    id: "basic",
                    name: "Basic",
                    tag: "Autonomía con guía",
                    price: "50€",
                    unit: "/mes",
                    claim: "Tú al mando, con estructura.",
                    features: [
                        "Cuestionario inicial escrito",
                        "Plan mensual de fuerza y prevención",
                        "Actualización mensual",
                        "Dudas puntuales por WhatsApp",
                    ],
                    cta: "Empezar ahora",
                    style: "bone",
                    msg: "basic",
                },
                {
                    id: "pro",
                    name: "Pro",
                    tag: "Seguimiento cercano",
                    badge: "El más vendido",
                    price: "95€",
                    unit: "/mes",
                    claim: "Tu plan, vivo cada semana.",
                    features: [
                        "Valoración inicial",
                        "Adaptado a tu calendario y material",
                        "Actualización quincenal",
                        "Revisión continuada de carga",
                        "Videollamada mensual",
                    ],
                    cta: "Empezar ahora",
                    style: "featured",
                    msg: "pro",
                },
                {
                    id: "duo",
                    name: "Duo",
                    tag: "Pro, para dos",
                    price: "80€",
                    unit: "/jugador",
                    claim: "Todo lo del Pro, para dos.",
                    features: [
                        "Para dos jugadores del mismo equipo",
                        "Mismo calendario, planes distintos: cada uno entrena lo que necesita",
                        "Mismo seguimiento, mejor precio",
                    ],
                    cta: "Empezar ahora",
                    style: "bone",
                    msg: "duo",
                },
                {
                    id: "elite",
                    name: "Elite",
                    tag: "Máximo seguimiento",
                    price: "220€",
                    unit: "/mes",
                    claim: "Sólo 2 plazas por temporada.",
                    features: [
                        "Todo lo del Pro",
                        "Actualización y videollamada semanal",
                        "WhatsApp prioritario",
                        "Activación pre-partido y check-in post",
                        "Nutrición incluida (guía + seguimiento)",
                        "Coordinación con tu club o fisio",
                        "Informe mensual de tu temporada",
                    ],
                    cta: "Pedir plaza",
                    style: "dark",
                    msg: "elite",
                },
            ],
            compare: {
                label: "Compara los planes al detalle",
                rows: [
                    ["Plan de fuerza y prevención personalizado", "✓", "✓", "✓"],
                    ["Adaptado a tu calendario y a tu material", "—", "✓", "✓"],
                    ["Actualización del plan", "Mensual", "Quincenal", "Semanal"],
                    ["Valoración inicial", "Cuestionario", "✓", "✓"],
                    ["Registro de entreno y wellness", "—", "✓", "✓"],
                    ["Revisión continuada de carga", "—", "✓", "✓"],
                    ["Videollamada de seguimiento", "—", "Mensual", "Semanal"],
                    ["Contacto por WhatsApp", "Dudas puntuales", "Según horario", "Prioritario"],
                    ["Activación pre-partido y recuperación post", "—", "—", "✓"],
                    ["Check-in post-partido", "—", "—", "✓"],
                    ["Nutrición (guía + seguimiento)", "—", "—", "Incluido"],
                    ["Coordinación con tu club o fisio", "—", "—", "✓"],
                    ["Informe mensual de tu temporada", "—", "—", "✓"],
                ],
            },
            band: {
                pre: "¿Dudas entre dos planes?",
                strong: "Escríbenos y te decimos cuál encaja contigo.",
                cta: "Hablar por WhatsApp",
            },
        },
        nutricion: {
            eyebrow: "Amplía tu control",
            title: "Súmale la nutrición",
            text: "Guía nutricional por un pago único de 35 € en Basic, Pro y Duo: hábitos, estructura y timing para entrenar y competir mejor. En Elite va incluida, con seguimiento.",
            price: "35€",
            unit: "pago único",
            cta: "Empezar ahora",
        },
        prueba: {
            eyebrow: "Prueba · Programa 01 → 02",
            titlePre: "palabra de",
            titleEm: "jugador.",
            quote: "El trabajo de cada semana se nota el día del partido.",
            photoLabel: "Foto del atleta",
            athletes: [
                { meta: "Alex Almenta · 2ª FEB", img: "/images/athlete-1.jpg", team: "" },
                { meta: "Nombre · Liga · Posición", img: "/images/athlete-2.jpg", team: "" },
                { meta: "Nombre · Liga · Posición", team: "" },
                { meta: "Nombre · Liga · Posición", team: "" },
            ],
            teamPending: "Equipo — pendiente",
        },
        faq: {
            eyebrow: "Dudas frecuentes",
            titlePre: "lo que todos",
            titleEm: "preguntan.",
            items: [
                {
                    q: "¿Puede ser mi única preparación física?",
                    a: "Sí. El plan cubre fuerza, prevención y preparación completa para tu temporada. Si no tienes preparador en el club, esto es tu estructura entera.",
                },
                {
                    q: "¿Y si mi club ya tiene preparador?",
                    a: "Mejor. Complementamos el trabajo del club con lo individual — tu carga, tus molestias, tu semana. En Elite nos coordinamos directamente con tu club.",
                },
                {
                    q: "¿Y si no tengo gimnasio?",
                    a: "El plan se diseña con el material que tienes de verdad. Lo que no vamos a hacer es darte un plan que no puedas cumplir.",
                },
                {
                    q: "¿Puedo empezar a mitad de temporada?",
                    a: "Sí. La valoración inicial sirve exactamente para eso: saber dónde estás hoy y construir desde ahí.",
                },
                {
                    q: "¿Cuánto tiempo me va a pedir por semana?",
                    a: "Normalmente 2 a 4 sesiones que encajan alrededor de tus entrenos de equipo. El plan se adapta a tu semana, no al revés.",
                },
                {
                    q: "¿Qué pasa si me lesiono o tengo que parar?",
                    a: "No hay permanencia: si necesitas parar, simplemente no renuevas el mes siguiente. Y si es una molestia leve, ajustamos el plan para seguir trabajando lo que sí puedas.",
                },
                {
                    q: "¿Cómo funcionan los pagos?",
                    a: "Mensualidad, sin permanencia y sin letra pequeña. Empiezas cuando quieras y cambias de plan cuando tu temporada lo pida.",
                },
            ],
        },
        empezar: {
            eyebrow: "Empezar",
            titlePre: "¿empezamos?",
            titleEm: "escríbenos",
            titlePost: "y lo hablamos.",
            subPre:
                "Cuéntanos tu momento y tu calendario. Te decimos qué plan encaja contigo —",
            subStrong: "sin compromiso.",
            responsePre: "Te respondemos en",
            responseStrong: "menos de 24h.",
            countries: { es: "España", pt: "Portugal" },
            legal: "Precios y condiciones actuales. El acompañamiento nutricional es educativo y no sustituye la valoración de un nutricionista colegiado.",
        },
        footer: { motto1: "Nada porque sí.", motto2: "Todo por una razón." },
        sobre: {
            eyebrow: "Sobre nosotros",
            titlePre: "las personas detrás de",
            titleEm: "arc.lab.",
            photoLabel: "Foto del equipo — pendiente",
            people: [
                {
                    handle: "@uxisureda",
                    zone: "España",
                    bio: "[Bio pendiente — una línea sobre ti]",
                },
                {
                    handle: "@gmorais.24",
                    zone: "Portugal",
                    bio: "[Bio pendiente — una línea sobre ti]",
                },
            ],
        },
    },
};
